# Generated by Django 2.2.2 on 2019-09-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20190703_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bhutia',
            options={'managed': False, 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterModelTable(
            name='bhutia',
            table='Bhutia',
        ),
    ]
