# Generated by Django 2.2.2 on 2019-10-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20190918_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bhutia',
            options={'managed': False, 'verbose_name': 'Bhutia Entry', 'verbose_name_plural': 'Bhutia'},
        ),
    ]
