# Generated by Django 2.2.2 on 2019-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('romanization', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ipa', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('tib_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('bhut_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('example', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Word',
                'managed': False,
            },
        ),
    ]
