# Generated by Django 2.2.2 on 2019-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhutia',
            fields=[
                ('romanization', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ipa', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('tib_script', models.CharField(blank=True, max_length=100, null=True)),
                ('example', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Word',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
